# https://github.com/touist/touist/blob/1b1c2ef709ce906eb2ba581c6ec840746bb884b9/circle.yml

language: node_js

env:
  - DVISVGM_URL=https://github.com/mgieseki/dvisvgm/releases/download/2.6/dvisvgm-2.6.tar.gz

cache:
  directories:
    - $HOME/.dvisvgm

before_install:
  # This PPA is a backport of TeXLive 2016 to Ubuntu 14.04 Trusty, which only
  # has packages for TexLive 2013.
  - sudo add-apt-repository -y ppa:jonathonf/texlive-2016

  # Update package repositories.
  - sudo apt-get update -qq

# Install the dependencies for TeXLive and dvisvgm.
  - sudo apt-get install -y --no-install-recommends libkpathsea-dev
      libpotrace-dev curl texlive texlive-xetex texlive-extra-utils
      texlive-latex-extra texlive-generic-extra texlive-math-extra lmodern

install:
  # Install dvisvgm in a cached directory if it doesn't already exist.
  - sh install-dvisvgm.sh

script:
- npm install madoko -g
- madoko doc.md
