dd:
  secure: CEaUE773a8F5u+9e+qoMwipebXn2LLgrh6Q8y0h0dZ5JyBkUpnJfq+AZSaCIyMvKLpLNsFMESyFu+Wm2I9S2kdIT2BfOnLnlFXfYaX0j8GkXgiemmMzEYKhzE/Slq1nqOiSWNf2UwlsQj8rJw7+lMD+5gs50Hl43JTBAeUDOZfk=
language: node_js
node_js:
- '0.10'
script:
- echo $HELLO
- sudo apt-get install sshpass
- npm install madoko -g
- madoko doc.md
after_success:
- sshpass -p "$PASSWD" scp doc.html sg875@users.hszk.bme.hu:public_html/remo/
