# Sources of inspiration for this file:
# * https://github.com/touist/touist/blob/1b1c2ef709ce906eb2ba581c6ec840746bb884b9/circle.yml

language: node_js

env:
  - DVISVGM_URL=https://github.com/mgieseki/dvisvgm/releases/download/2.6/dvisvgm-2.6.tar.gz

cache:
  # Caching packages: https://stackoverflow.com/a/52425687
  apt: true
  # Caching directories: https://docs.travis-ci.com/user/caching/#arbitrary-directories
  directories:
    - $HOME/.dvisvgm

addons:
  apt:
    # Safelist: https://github.com/travis-ci/apt-package-safelist/blob/master/ubuntu-trusty
    packages:
      - curl
      - libkpathsea-dev
      - libpotrace-dev
      - lmodern

before_install:
  # This PPA has a backport of TeXLive 2016 to Ubuntu 14.04 Trusty, which only
  # has packages for TexLive 2013.
  - sudo add-apt-repository -y ppa:jonathonf/texlive-2016

  # Update package repositories.
  - sudo apt-get update -qq

  # Install the dependencies for TeXLive and dvisvgm.
  - sudo apt-get install -qq --no-install-recommends
      texlive texlive-xetex texlive-extra-utils
      texlive-latex-extra texlive-generic-extra texlive-math-extra

install:
  # Build and install dvisvgm if it isn't already there.
  - sh install-dvisvgm.sh

  # Check for dvisvgm installation
  - dvisvgm --version

  # Install madoko
  - npm install madoko -g

  # Check for madoko installation
  - madoko --version

script:
  - madoko doc.md
