# Sources of inspiration for this file:
# * https://github.com/touist/touist/blob/1b1c2ef709ce906eb2ba581c6ec840746bb884b9/circle.yml

language: node_js

env:
  global:
    - DVISVGM_URL=https://github.com/mgieseki/dvisvgm/releases/download/2.6/dvisvgm-2.6.tar.gz
    - secure: "v3MB9EpJtwDN7BHlHuf+8ddEA+JaGjjvyXMsC23G6KrDvDFEZV2oSOx3IztZW0N7cLARDufKiWazkjzX8afkhyOARht8pKCfQL1UL6swFlLrc/uVQXVtfOKBMn5wcBIYsh9VG2gSdYz98yapdDJb1siKFcP/Ki2iWH37NAR21PPnxMMqFyMWS/ZWdBt0hgsEC9zVCaBetov+x+LcKKV8bp4u5n6qKQ0gpjFUYVS7Le0j+ai/AmbaIJCN1ClToEfQsLtE7qKKFof6wOyYpYTgaAGR4Vm2aux+NFeVTZaamHpEQyl2/NAaAxYsb2WQZUYAAdLepGr19n2jrujQOuIRjLBaLUUZA3eTek54lStdjxQZ94pYC5cErr/r8SwYu2wG7ReoQxj/uywW5qWzYKAO/bRi7BZntXpC9WmU9oF0jKGnfE23P1Y9FRweuGz/CrROA5T+z6y2gl6uqtt1bLcbEQTy2lmA570dcpe54+vz/PqpNMVptd3HK8VS5DizBf8UcOCYHIRN6qfpWGsdI9/pXnt4uq5GHOzMZy+eHpWv2SefcFjFEmyuJb2psujqImp5jpKVnqJcHs0u7sijF6cNhBKlnCCoY+KKwGcXb+Zo/D4bAjumJ6KxXaDUvPLKDcU1LTEB8FikMUVt9r0CcnOImzznTGzOqT2ULexaKHd4kS4="

cache:
  # Caching packages: https://stackoverflow.com/a/52425687
  apt: true
  # Caching directories: https://docs.travis-ci.com/user/caching/#arbitrary-directories
  directories:
    # dvisvgm build
    - $HOME/.dvisvgm
    # apt-get package cache: https://stackoverflow.com/a/52446551
    - $HOME/.aptcache

addons:
  apt:
    # Newer gcc/g++:
    #   * https://docs.travis-ci.com/user/languages/c/#gcc-on-linux
    #   * https://gist.github.com/cotsog/19cd36b295e03bdbabdb
    sources:
      - ubuntu-toolchain-r-test
    # Safelist: https://github.com/travis-ci/apt-package-safelist/blob/master/ubuntu-trusty
    packages:
      # For downloading dvisvgm
      - curl
      # Minimum gcc and g++ versions required for dvisvgm
      - gcc-4.9
      - g++-4.9
      # For emailing PDF
      - heirloom-mailx

before_install:

  # Cached packages: move to apt archive.
  - if [ -e $HOME/.aptcache/*.deb ]; then sudo mv $HOME/.aptcache/*.deb /var/cache/apt/archives/; fi

  # This PPA has a backport of TeXLive 2016 to Ubuntu 14.04 Trusty, which only
  # has packages for TexLive 2013.
  - sudo -E add-apt-repository -y ppa:jonathonf/texlive-2016

  # Update package repositories.
  - travis_apt_get_update

  # Install the PPA dependencies for TeXLive and dvisvgm.
  - travis_retry sudo -E apt-get -yq --no-install-suggests --no-install-recommends
      $(travis_apt_get_options) install
      libkpathsea-dev texlive texlive-xetex texlive-extra-utils
      texlive-latex-extra texlive-generic-extra texlive-math-extra lmodern

  # Cached packages: copy from apt archive.
  - cp /var/cache/apt/archives/*deb $HOME/.aptcache/

install:

  # Check xelatex version
  - xelatex --version

  # Build and install dvisvgm if it isn't already there.
  - sh install-dvisvgm.sh
  - dvisvgm --version

  # Install madoko
  - npm install madoko -g

  # Check madoko version
  - madoko --version

script:

  # Run madoko
  - madoko doc.md

  # Email PDF
  - mailx -s "travis-madoko pdf" -a doc.pdf "$MAILX_DST"
