# Sources of inspiration for this file:
# * https://github.com/touist/touist/blob/1b1c2ef709ce906eb2ba581c6ec840746bb884b9/circle.yml

language: node_js

env:
  global:
    - DVISVGM_VERSION=2.6.1
    - DVISVGM_URL=https://github.com/mgieseki/dvisvgm/releases/download/$DVISVGM_VERSION/dvisvgm-$DVISVGM_VERSION.tar.gz

cache:
  # Caching directories: https://docs.travis-ci.com/user/caching/#arbitrary-directories
  directories:
    # dvisvgm build
    - $HOME/.dvisvgm
    # apt-get package cache: https://stackoverflow.com/a/52446551
    - $HOME/.aptcache

before_install:

    # This PPA is used for newer gcc/g++ (4.9 in our case):
    #   * https://docs.travis-ci.com/user/languages/c/#gcc-on-linux
    #   * https://gist.github.com/cotsog/19cd36b295e03bdbabdb
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"

  # This PPA has a backport of TeXLive 2016 to Ubuntu 14.04 Trusty, which only
  # has packages for TexLive 2013.
  - sudo -E apt-add-repository -y "ppa:jonathonf/texlive-2016"

  # Update package repositories.
  - travis_apt_get_update

  # Cached packages: restore by installing with dpkg:
  # https://unix.stackexchange.com/a/159114
  - (cd $HOME/.aptcache; if [ "$(ls -A)" != "" ]; then sudo dpkg -i *.deb; fi)

  # Install package dependencies. We install all packages here instead of using
  # the travis.yml apt mechanism because the latter does not seem to add any
  # benefit such as caching.
  - travis_retry sudo -E apt-get -yq --no-install-suggests --no-install-recommends
      $(travis_apt_get_options) install -f
      curl
      python3-dev python3-pip
      gcc-4.9 g++-4.9
      libkpathsea-dev texlive texlive-xetex texlive-extra-utils
      texlive-latex-extra texlive-generic-extra texlive-math-extra lmodern

  # Cached packages: copy from apt archive.
  - cp /var/cache/apt/archives/*.deb $HOME/.aptcache/

install:

  # Install client for send.firefox.com. It requires an updated setuptools.
  - sudo pip3 install --upgrade setuptools
  - sudo pip3 install sendclient

  # Check xelatex version
  - xelatex --version | tee /dev/stderr | head -1 | grep "TeX Live 2016" > /dev/null

  # Build and install dvisvgm if it isn't already there.
  - sh install-dvisvgm.sh

  # Install madoko
  - npm install madoko -g

  # Check madoko version
  - madoko --version

script:

  # Run madoko
  - madoko --pdf -vv --odir=out doc.md

  # Send PDF to send.firefox.com
  - send-cli out/doc.pdf
